FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    openssh-server \
    supervisor \
    sudo \
    vim \
    && rm -rf /var/lib/apt/lists/*

# python dependencies
RUN pip3 install --no-cache-dir \
    Flask==2.3.2 \
    PyJWT==2.8.0 \
    lxml==4.9.3 \
    reportlab==4.0.4

RUN mkdir /var/run/sshd

# enable password auth
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config

# create a peter user (weak pwd)
RUN useradd -m -s /bin/bash peter && \
    echo "peter:iloveoscar" | chpasswd

# misconfigure sudo for peter user
RUN echo "peter ALL=(root) NOPASSWD: /usr/bin/vim" > /etc/sudoers.d/peter && \
    chmod 440 /etc/sudoers.d/peter

WORKDIR /app
COPY . .
COPY flag.txt /flag.txt
COPY root.txt /root/root.txt
RUN chmod 600 /root/root.txt
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN chmod -R 555 /app

EXPOSE 22 5000

CMD ["/usr/bin/supervisord"]
